PRODUCTS = [
            'Notebook Acer Aspire 5', 'Smartphone Samsung Galaxy S20', 'Smart TV LG 50 polegadas', 
            'Mouse Logitech MX Master', 'Fone de Ouvido Sony WH-1000XM4', 'Teclado Mecânico Corsair K95', 
            'Câmera Digital Canon EOS Rebel T7', 'Headset HyperX Cloud II', 'Monitor Gamer Alienware 34"', 
            'Tablet Samsung Galaxy Tab S7', 'Caixa de Som Bluetooth JBL Flip 5', 'Impressora HP Deskjet 3755', 
            'Smartwatch Apple Watch Series 6', 'Drone DJI Mavic Air 2', 'Roçadeira Elétrica Tramontina', 
            'Notebook Dell Inspiron 15', 'Smartphone Motorola Moto G Power', 'Smart TV Sony 55 polegadas', 
            'Mouse Pad Gamer Corsair MM300', 'Fone de Ouvido JBL Tune 750BTNC', 'Teclado sem Fio Logitech K780',
            'Câmera de Segurança Nest Cam IQ', 'Headset Razer Kraken Tournament', 'Monitor LG UltraWide 29"',
            'Tablet Amazon Fire HD 10', 'Caixa de Som Sony SRS-XB43', 'Impressora Epson EcoTank L3150',
            'Smartwatch Samsung Galaxy Watch 3', 'Drone DJI Mini 2', 'Aparador de Grama Tramontina', 
            'Notebook HP Pavilion 15', 'Smartphone Apple iPhone SE', 'Smart TV TCL 50 polegadas', 
            'Mouse Logitech G502 HERO', 'Fone de Ouvido Bose QuietComfort 35 II', 
            'Teclado Mecânico Razer BlackWidow Elite', 'Câmera de Ação GoPro HERO9 Black', 
            'Headset SteelSeries Arctis 7', 'Monitor Dell UltraSharp 27"', 'Tablet Apple iPad Air', 
            'Caixa de Som JBL Xtreme 3', 'Impressora Brother MFC-L2750DW', 'Smartwatch Fitbit Versa 3', 
            'Drone DJI Mavic Mini', 'Aspirador de Pó Robô iRobot Roomba i3+', 'Notebook Asus Zenbook UX425', 
            'Smartphone OnePlus 8T', 'Smart TV Samsung 55 polegadas', 'Mouse Pad Gamer Razer Goliathus',
            'Fone de Ouvido Sennheiser Momentum True Wireless 2', 'Teclado sem Fio Logitech K810', 
            'Câmera Mirrorless Sony Alpha a7 III', 'Headset Astro A50 Wireless', 'Monitor Asus TUF Gaming 24,5"', 
            'Tablet Microsoft Surface Pro 7', 'Caixa de Som Ultimate Ears BOOM 3', 'Impressora Canon PIXMA TS9120', 
            'Smartwatch Garmin Venu', 'Drone DJI Phantom 4', 'Lavadora de Alta Pressão Karcher K4', 
            'Notebook Lenovo IdeaPad 5', 'Smartphone Xiaomi Redmi Note 9 Pro', 'Smart TV LG OLED 55 polegadas', 
            'Mouse sem Fio Logitech MX Anywhere 2S', 'Fone de Ouvido Jabra Elite 85h', 
            'Teclado Mecânico HyperX Alloy FPS Pro', 'Câmera de Segurança Arlo Pro 3', 'Headset Turtle Beach Stealth 700', 
            'Monitor Acer Nitro XV272U']

CATEGORIES = ['Eletrônicos', 'Informática', 'Celulares', 'Acessórios'] 